version: "3.7"
services:
    gentree_php:
        user: dev:dev
        container_name: gentree_php
        build: ./docker_config/php
        restart: always
        volumes:
            - ./${BACKEND_APP}:/var/www/gentree
            - ./docker_config/php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
        working_dir: /var/www/gentree
        ports:
            - "10181:9000"
        networks:
            gentree_network:
                aliases:
                    - gentree_php

networks:
    gentree_network: